import { useNavigate } from 'react-router-dom'

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: `By accessing or using InsightsHub ("the Platform"), you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you must not use the Platform. These terms apply to all users, including visitors, registered users, and paying subscribers.`,
  },
  {
    title: '2. Description of Service',
    content: `InsightsHub is an AI-powered document Q&A platform that allows users to upload documents (PDF, CSV, TXT, DOCX), extract and store content, and query that content using natural language. Documents are processed by extracting text chunks stored in database, with semantic embeddings stored in a vector database. AI-generated answers are produced via cloud-hosted Large Language Models (LLMs) provided by Groq.`,
  },
  {
    title: '3. User Accounts & Authentication',
    content: `InsightsHub uses Google OAuth for authentication. By signing in, you authorise us to access your Google account's name, email address, and profile picture solely for the purpose of account creation and identification. You are responsible for maintaining the confidentiality of your account and for all activities that occur under your account. You must notify us immediately of any unauthorised use of your account.`,
  },
  {
    title: '4. Document Upload & Data Processing',
    content: `When you upload documents to InsightsHub, you grant us a limited, non-exclusive licence to process, store, and index the content solely to provide the service to you. Uploaded files are stored securely in ElasticLake object storage. Extracted text chunks are stored in MongoDB, and semantic embeddings are stored in Qdrant. You retain full ownership of all content you upload. You must not upload documents containing illegal content, content that violates third-party rights, or any personally sensitive data of individuals without their consent.`,
  },
  {
    title: '5. Subscription & Payments',
    content: `InsightsHub offers subscription plans billed on a monthly basis. Payments are processed securely via Razorpay. By subscribing, you agree to the following:

• Subscriptions are charged upfront for one full calendar month from the date of purchase.
• Payments are non-refundable once made. No partial refunds are provided for unused days.
• You cannot upgrade, downgrade, or switch plans while a plan is currently active. Plan changes are only permitted after your current plan expires.
• There is no automatic renewal. To continue using premium features, you must manually purchase a new plan upon expiry.
• InsightsHub reserves the right to modify pricing for future billing cycles with prior notice.`,
  },
  {
    title: '6. Acceptable Use',
    content: `You agree not to misuse the Platform. Prohibited activities include:

• Uploading malicious files or attempting to exploit the document processing pipeline.
• Using the Platform to generate, distribute, or store illegal, defamatory, or harmful content.
• Attempting to reverse-engineer, scrape, or extract the underlying AI models or database structures.
• Sharing your account credentials with others or reselling access to the Platform.
• Using the Platform in any way that could damage, disable, or impair its infrastructure.`,
  },
  {
    title: '7. AI-Generated Content Disclaimer',
    content: `Answers generated by InsightsHub are produced by AI and are based solely on the documents you have uploaded. These answers may not always be accurate, complete, or up to date. InsightsHub is not liable for decisions made based on AI-generated responses. You should verify critical information independently. The AI does not retain memory between sessions and answers are grounded only in your uploaded document content.`,
  },
  {
    title: '8. Intellectual Property',
    content: `The InsightsHub platform, including its design, codebase, branding, and user interface, is owned by InsightsHub and protected by applicable intellectual property laws. You may not copy, reproduce, or create derivative works from any part of the Platform without prior written consent. All document content you upload remains your intellectual property.`,
  },
  {
    title: '9. Termination',
    content: `InsightsHub reserves the right to suspend or terminate your account at any time if you violate these Terms. Upon termination, your access to the Platform will cease, and your stored data may be deleted. You may stop using the Platform at any time; however, no refunds will be issued for active subscription periods.`,
  },
  {
    title: '10. Limitation of Liability',
    content: `To the maximum extent permitted by applicable law, InsightsHub shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of data, revenue, or business opportunities, arising from your use of the Platform. Our total liability shall not exceed the amount paid by you in the three months preceding the claim.`,
  },
  {
    title: '11. Governing Law',
    content: `These Terms are governed by and construed in accordance with the laws of India. Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts located in India. Users outside India access the Platform voluntarily and are responsible for compliance with local laws.`,
  },
  {
    title: '12. Changes to Terms',
    content: `InsightsHub reserves the right to update these Terms at any time. We will notify users of significant changes via email or a notice on the Platform. Continued use of the Platform after any changes constitutes your acceptance of the updated Terms.`,
  },
  {
    title: '13. Contact Us',
    content: `If you have any questions about these Terms and Conditions, please contact us:\n\nEmail: shovansahu000@gmail.com\nWebsite: https://insightshub.in`,
  },
]

export default function TermsPage() {
  const navigate = useNavigate()

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg-primary)', color: 'var(--text-primary)', overflowX: 'hidden' }}>

      {/* NAV */}
      <nav style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '0 20px', height: 60,
        borderBottom: '1px solid var(--border)',
        position: 'sticky', top: 0, zIndex: 200,
        background: 'rgba(10,10,15,0.85)', backdropFilter: 'blur(12px)',
      }}>
        <div
          onClick={() => navigate('/')}
          style={{ display: 'flex', alignItems: 'center', gap: 10, cursor: 'pointer' }}
        >
          <div style={{ width: 34, height: 34, flexShrink: 0 }}>
            <img src="/favicon.svg" alt="InsightsHub logo" style={{ width: 34, height: 34 }} />
          </div>
          <span style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 18 }}>
            Insights<span style={{ color: 'var(--accent)' }}>Hub</span>
          </span>
        </div>
        <button
          onClick={() => navigate('/')}
          style={{
            padding: '8px 20px', borderRadius: 'var(--radius-md)',
            background: 'transparent', border: '1px solid var(--border-light)',
            color: 'var(--text-primary)', fontSize: 14, transition: 'var(--transition)',
            cursor: 'pointer',
          }}
          onMouseEnter={e => { e.currentTarget.style.borderColor = 'var(--accent)'; e.currentTarget.style.color = 'var(--accent)' }}
          onMouseLeave={e => { e.currentTarget.style.borderColor = 'var(--border-light)'; e.currentTarget.style.color = 'var(--text-primary)' }}
        >
          ← Back to Home
        </button>
      </nav>

      {/* HERO */}
      <section style={{
        maxWidth: 860, margin: '0 auto', padding: '64px 24px 40px',
        textAlign: 'center', animation: 'fadeIn 0.6s ease forwards',
      }}>
        <div style={{
          display: 'inline-block', padding: '6px 16px', borderRadius: 999,
          background: 'var(--accent-dim)', border: '1px solid rgba(108,99,255,0.3)',
          color: 'var(--accent)', fontSize: 13, fontWeight: 500, marginBottom: 24,
          letterSpacing: '0.04em',
        }}>
          📋 Legal
        </div>
        <h1 style={{
          fontFamily: 'var(--font-display)', fontSize: 'clamp(2rem, 5vw, 3rem)',
          fontWeight: 800, lineHeight: 1.1, letterSpacing: '-0.03em', marginBottom: 16,
        }}>
          Terms &amp; Conditions
        </h1>
        <p style={{ color: 'var(--text-muted)', fontSize: 14, marginBottom: 12 }}>
          Last updated: {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
        </p>
        <p style={{
          color: 'var(--text-secondary)', fontSize: 15, lineHeight: 1.7,
          maxWidth: 580, margin: '0 auto',
        }}>
          Please read these terms carefully before using InsightsHub. By using the platform, you agree to be bound by these terms.
        </p>
      </section>

      {/* CONTENT */}
      <section style={{ maxWidth: 780, margin: '0 auto', padding: '20px 24px 80px' }}>
        {sections.map((s, i) => (
          <div
            key={i}
            style={{
              background: 'var(--bg-card)', border: '1px solid var(--border)',
              borderRadius: 'var(--radius-lg)', padding: '28px 32px',
              marginBottom: 12, transition: 'var(--transition)',
            }}
            onMouseEnter={e => { e.currentTarget.style.borderColor = 'rgba(108,99,255,0.4)' }}
            onMouseLeave={e => { e.currentTarget.style.borderColor = 'var(--border)' }}
          >
            <h2 style={{
              fontFamily: 'var(--font-display)', fontSize: 17, fontWeight: 700,
              color: 'var(--text-primary)', marginBottom: 12,
            }}>
              {s.title}
            </h2>
            <p style={{
              color: 'var(--text-secondary)', fontSize: 14, lineHeight: 1.85,
              whiteSpace: 'pre-line', margin: 0,
            }}>
              {s.content}
            </p>
          </div>
        ))}

        <div style={{
          marginTop: 8, padding: '24px 32px',
          background: 'var(--bg-card)', border: '1px solid var(--border)',
          borderRadius: 'var(--radius-lg)', textAlign: 'center',
        }}>
          <p style={{ color: 'var(--text-secondary)', fontSize: 14, margin: 0 }}>
            Also read our{' '}
            <span
              onClick={() => navigate('/privacy')}
              style={{ color: 'var(--accent)', cursor: 'pointer', fontWeight: 600 }}
            >
              Privacy Policy
            </span>
            {' '}to understand how we handle your data.
          </p>
        </div>
      </section>

      {/* FOOTER */}
      <footer style={{
        borderTop: '1px solid var(--border)',
        padding: '28px 24px',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        flexWrap: 'wrap', gap: 12,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{ width: 28, height: 28 }}>
            <img src="/favicon.svg" alt="InsightsHub logo" style={{ width: 28, height: 28 }} />
          </div>
          <span style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 15 }}>
            Insights<span style={{ color: 'var(--accent)' }}>Hub</span>
          </span>
        </div>
        <p style={{ fontSize: 13, color: 'var(--text-muted)' }}>
          Made with <span style={{ color: 'var(--danger)' }}>♥</span> by{' '}
          <span style={{ color: 'var(--text-secondary)', fontWeight: 500 }}>Shovan</span>
        </p>
        <p style={{ color: 'var(--text-muted)', fontSize: 13 }}>
          © {new Date().getFullYear()} InsightsHub · Your knowledge, amplified by AI.
        </p>
      </footer>

    </div>
  )
}